services:
  - type: web
    name: rmm-dashboard-2
    runtime: docker
    repo: https://github.com/daley21233/rmm-dashboard
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: your-super-secret-key-change-this
